version: '2'
services:
  db:
    image: "mrlesmithjr/mysql"
    volumes:
      - "db:/var/lib/mysql"
    ports:
      - "33306:3306"
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: "powerdns"
      MYSQL_DATABASE: "powerdns"
      MYSQL_USER: "powerdns"
      MYSQL_PASSWORD: "powerdns"

  pdns-authoritative:
    depends_on:
      - "db"
      - "pdns-recursor"
    image: "mrlesmithjr/powerdns-authoritative:4.x"
    links:
      - "db"
      - "pdns-recursor"
    ports:
      - "53:53"
      - "53:53/udp"
      - "8081:8081"
    restart: "always"
    environment:
      PDNS_ALLOW_DDNS_UPDATE: "yes"
      PDNS_ALLOW_DDNS_UPDATE_FROM: "0.0.0.0/0"
      PDNS_API: "yes"
      PDNS_API_KEY: "changeme"
      PDNS_GMYSQL_DBNAME: "powerdns"
      PDNS_GMYSQL_HOST: "db"
      PDNS_GMYSQL_PASSWORD: "powerdns"
      PDNS_GMYSQL_USER: "powerdns"
      PDNS_LOG_DNS_QUERIES: "yes"
      PDNS_RECURSOR_SERVER: "pdns-recursor"
      PDNS_WEBSERVER_ADDRESS: "0.0.0.0"
      PDNS_WEBSERVER_PASSWORD: "changeme"
      PDNS_WEBSERVER_PORT: "8081"
      PDNS_WEBSERVER: "yes"

  pdns-recursor:
    image: "mrlesmithjr/powerdns-recursor:4.x"
    restart: "always"
    environment:
      PDNS_RECURSOR_LOCAL_ADDRESS: "0.0.0.0"

volumes:
  db:
