---
- hosts: localhost
  connection: local
  become: true
  vars:
    - pdns_download_url: 'https://downloads.powerdns.com/releases/deb'
  tasks:
    - name: Updating Apt-Cache
      apt:
        update_cache: yes

    - name: Installing ca-certificates
      apt:
        name: "ca-certificates"
        state: "latest"

    - name: Installing dumb-init
      apt:
        deb: "https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64.deb"

    - name: Installing Powerdns Pre-Reqs
      apt:
        name: "{{ item }}"
        state: "present"
        force: "yes"
      with_items:
        - 'dnsutils'
        - 'jq'
        - 'python-mysqldb'
        - 'mysql-client'

    - name: Adding PowerDNS Repo Key
      apt_key:
        url: "https://repo.powerdns.com/FD380FBB-pub.asc"
        state: "present"

    - name: Pinning PowerDNS Repo
      template:
        src: "/pdns_repo.j2"
        dest: "/etc/apt/preferences.d/pdns"

    - name: Adding PowerDNS Repo
      apt_repository:
        repo: "deb [arch=amd64] http://repo.powerdns.com/ubuntu {{ ansible_distribution_release|lower }}-auth-40 main"
        state: "present"

    - name: Installing PowerDNS Authoritative
      apt:
        name: "{{ item }}"
        state: "latest"
      with_items:
        - 'pdns-server'
        - 'pdns-backend-mysql'
